// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_rst
);


output   ap_ready;
input  [37:0] data_0_val;
input  [37:0] data_1_val;
input  [37:0] data_2_val;
input  [37:0] data_3_val;
input  [37:0] data_4_val;
input  [37:0] data_5_val;
input  [37:0] data_6_val;
input  [37:0] data_7_val;
input  [37:0] data_8_val;
input  [37:0] data_9_val;
input  [37:0] data_10_val;
input  [37:0] data_11_val;
input  [37:0] data_12_val;
input  [37:0] data_13_val;
input  [37:0] data_14_val;
input  [37:0] data_15_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
input   ap_rst;

wire   [0:0] icmp_ln45_fu_150_p2;
wire   [15:0] trunc_ln_fu_156_p4;
wire   [0:0] icmp_ln45_1_fu_174_p2;
wire   [15:0] trunc_ln46_1_fu_180_p4;
wire   [0:0] icmp_ln45_2_fu_198_p2;
wire   [15:0] trunc_ln46_2_fu_204_p4;
wire   [0:0] icmp_ln45_3_fu_222_p2;
wire   [15:0] trunc_ln46_3_fu_228_p4;
wire   [0:0] icmp_ln45_4_fu_246_p2;
wire   [15:0] trunc_ln46_4_fu_252_p4;
wire   [0:0] icmp_ln45_5_fu_270_p2;
wire   [15:0] trunc_ln46_5_fu_276_p4;
wire   [0:0] icmp_ln45_6_fu_294_p2;
wire   [15:0] trunc_ln46_6_fu_300_p4;
wire   [0:0] icmp_ln45_7_fu_318_p2;
wire   [15:0] trunc_ln46_7_fu_324_p4;
wire   [0:0] icmp_ln45_8_fu_342_p2;
wire   [15:0] trunc_ln46_8_fu_348_p4;
wire   [0:0] icmp_ln45_9_fu_366_p2;
wire   [15:0] trunc_ln46_9_fu_372_p4;
wire   [0:0] icmp_ln45_10_fu_390_p2;
wire   [15:0] trunc_ln46_s_fu_396_p4;
wire   [0:0] icmp_ln45_11_fu_414_p2;
wire   [15:0] trunc_ln46_10_fu_420_p4;
wire   [0:0] icmp_ln45_12_fu_438_p2;
wire   [15:0] trunc_ln46_11_fu_444_p4;
wire   [0:0] icmp_ln45_13_fu_462_p2;
wire   [15:0] trunc_ln46_12_fu_468_p4;
wire   [0:0] icmp_ln45_14_fu_486_p2;
wire   [15:0] trunc_ln46_13_fu_492_p4;
wire   [0:0] icmp_ln45_15_fu_510_p2;
wire   [15:0] trunc_ln46_14_fu_516_p4;
wire   [15:0] res_0_0_fu_166_p3;
wire   [15:0] res_1_0_fu_190_p3;
wire   [15:0] res_2_0_fu_214_p3;
wire   [15:0] res_3_0_fu_238_p3;
wire   [15:0] res_4_0_fu_262_p3;
wire   [15:0] res_5_0_fu_286_p3;
wire   [15:0] res_6_0_fu_310_p3;
wire   [15:0] res_7_0_fu_334_p3;
wire   [15:0] res_8_0_fu_358_p3;
wire   [15:0] res_9_0_fu_382_p3;
wire   [15:0] res_10_0_fu_406_p3;
wire   [15:0] res_11_0_fu_430_p3;
wire   [15:0] res_12_0_fu_454_p3;
wire   [15:0] res_13_0_fu_478_p3;
wire   [15:0] res_1445_0_fu_502_p3;
wire   [15:0] res_15_0_fu_526_p3;

assign ap_ready = 1'b1;

assign res_0_0_fu_166_p3 = ((icmp_ln45_fu_150_p2[0:0] == 1'b1) ? trunc_ln_fu_156_p4 : 16'd0);

assign res_10_0_fu_406_p3 = ((icmp_ln45_10_fu_390_p2[0:0] == 1'b1) ? trunc_ln46_s_fu_396_p4 : 16'd0);

assign res_11_0_fu_430_p3 = ((icmp_ln45_11_fu_414_p2[0:0] == 1'b1) ? trunc_ln46_10_fu_420_p4 : 16'd0);

assign res_12_0_fu_454_p3 = ((icmp_ln45_12_fu_438_p2[0:0] == 1'b1) ? trunc_ln46_11_fu_444_p4 : 16'd0);

assign res_13_0_fu_478_p3 = ((icmp_ln45_13_fu_462_p2[0:0] == 1'b1) ? trunc_ln46_12_fu_468_p4 : 16'd0);

assign res_1445_0_fu_502_p3 = ((icmp_ln45_14_fu_486_p2[0:0] == 1'b1) ? trunc_ln46_13_fu_492_p4 : 16'd0);

assign res_15_0_fu_526_p3 = ((icmp_ln45_15_fu_510_p2[0:0] == 1'b1) ? trunc_ln46_14_fu_516_p4 : 16'd0);

assign res_1_0_fu_190_p3 = ((icmp_ln45_1_fu_174_p2[0:0] == 1'b1) ? trunc_ln46_1_fu_180_p4 : 16'd0);

assign res_2_0_fu_214_p3 = ((icmp_ln45_2_fu_198_p2[0:0] == 1'b1) ? trunc_ln46_2_fu_204_p4 : 16'd0);

assign res_3_0_fu_238_p3 = ((icmp_ln45_3_fu_222_p2[0:0] == 1'b1) ? trunc_ln46_3_fu_228_p4 : 16'd0);

assign res_4_0_fu_262_p3 = ((icmp_ln45_4_fu_246_p2[0:0] == 1'b1) ? trunc_ln46_4_fu_252_p4 : 16'd0);

assign res_5_0_fu_286_p3 = ((icmp_ln45_5_fu_270_p2[0:0] == 1'b1) ? trunc_ln46_5_fu_276_p4 : 16'd0);

assign res_6_0_fu_310_p3 = ((icmp_ln45_6_fu_294_p2[0:0] == 1'b1) ? trunc_ln46_6_fu_300_p4 : 16'd0);

assign res_7_0_fu_334_p3 = ((icmp_ln45_7_fu_318_p2[0:0] == 1'b1) ? trunc_ln46_7_fu_324_p4 : 16'd0);

assign res_8_0_fu_358_p3 = ((icmp_ln45_8_fu_342_p2[0:0] == 1'b1) ? trunc_ln46_8_fu_348_p4 : 16'd0);

assign res_9_0_fu_382_p3 = ((icmp_ln45_9_fu_366_p2[0:0] == 1'b1) ? trunc_ln46_9_fu_372_p4 : 16'd0);

assign trunc_ln46_10_fu_420_p4 = {{data_11_val[25:10]}};

assign trunc_ln46_11_fu_444_p4 = {{data_12_val[25:10]}};

assign trunc_ln46_12_fu_468_p4 = {{data_13_val[25:10]}};

assign trunc_ln46_13_fu_492_p4 = {{data_14_val[25:10]}};

assign trunc_ln46_14_fu_516_p4 = {{data_15_val[25:10]}};

assign trunc_ln46_1_fu_180_p4 = {{data_1_val[25:10]}};

assign trunc_ln46_2_fu_204_p4 = {{data_2_val[25:10]}};

assign trunc_ln46_3_fu_228_p4 = {{data_3_val[25:10]}};

assign trunc_ln46_4_fu_252_p4 = {{data_4_val[25:10]}};

assign trunc_ln46_5_fu_276_p4 = {{data_5_val[25:10]}};

assign trunc_ln46_6_fu_300_p4 = {{data_6_val[25:10]}};

assign trunc_ln46_7_fu_324_p4 = {{data_7_val[25:10]}};

assign trunc_ln46_8_fu_348_p4 = {{data_8_val[25:10]}};

assign trunc_ln46_9_fu_372_p4 = {{data_9_val[25:10]}};

assign trunc_ln46_s_fu_396_p4 = {{data_10_val[25:10]}};

assign trunc_ln_fu_156_p4 = {{data_0_val[25:10]}};

assign ap_return_0 = res_0_0_fu_166_p3;

assign ap_return_1 = res_1_0_fu_190_p3;

assign ap_return_10 = res_10_0_fu_406_p3;

assign ap_return_11 = res_11_0_fu_430_p3;

assign ap_return_12 = res_12_0_fu_454_p3;

assign ap_return_13 = res_13_0_fu_478_p3;

assign ap_return_14 = res_1445_0_fu_502_p3;

assign ap_return_15 = res_15_0_fu_526_p3;

assign ap_return_2 = res_2_0_fu_214_p3;

assign ap_return_3 = res_3_0_fu_238_p3;

assign ap_return_4 = res_4_0_fu_262_p3;

assign ap_return_5 = res_5_0_fu_286_p3;

assign ap_return_6 = res_6_0_fu_310_p3;

assign ap_return_7 = res_7_0_fu_334_p3;

assign ap_return_8 = res_8_0_fu_358_p3;

assign ap_return_9 = res_9_0_fu_382_p3;

assign icmp_ln45_10_fu_390_p2 = (($signed(data_10_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_11_fu_414_p2 = (($signed(data_11_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_12_fu_438_p2 = (($signed(data_12_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_13_fu_462_p2 = (($signed(data_13_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_14_fu_486_p2 = (($signed(data_14_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_15_fu_510_p2 = (($signed(data_15_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_1_fu_174_p2 = (($signed(data_1_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_2_fu_198_p2 = (($signed(data_2_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_3_fu_222_p2 = (($signed(data_3_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_4_fu_246_p2 = (($signed(data_4_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_5_fu_270_p2 = (($signed(data_5_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_6_fu_294_p2 = (($signed(data_6_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_7_fu_318_p2 = (($signed(data_7_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_8_fu_342_p2 = (($signed(data_8_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_9_fu_366_p2 = (($signed(data_9_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_150_p2 = (($signed(data_0_val) > $signed(38'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s
