-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_10_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_12_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_13_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_14_val : IN STD_LOGIC_VECTOR (37 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (37 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of myproject_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv38_0 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_156_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_1_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_1_fu_180_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_2_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_2_fu_204_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_3_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_3_fu_228_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_4_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_4_fu_252_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_5_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_5_fu_276_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_6_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_6_fu_300_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_7_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_7_fu_324_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_8_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_8_fu_348_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_9_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_9_fu_372_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_10_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_s_fu_396_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_11_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_10_fu_420_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_12_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_11_fu_444_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_13_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_12_fu_468_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_14_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_13_fu_492_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_15_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_14_fu_516_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_0_0_fu_166_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_1_0_fu_190_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_2_0_fu_214_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_3_0_fu_238_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_4_0_fu_262_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_5_0_fu_286_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_6_0_fu_310_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_7_0_fu_334_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_8_0_fu_358_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_9_0_fu_382_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_10_0_fu_406_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_11_0_fu_430_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_12_0_fu_454_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_13_0_fu_478_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_1445_0_fu_502_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_15_0_fu_526_p3 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= res_0_0_fu_166_p3;
    ap_return_1 <= res_1_0_fu_190_p3;
    ap_return_10 <= res_10_0_fu_406_p3;
    ap_return_11 <= res_11_0_fu_430_p3;
    ap_return_12 <= res_12_0_fu_454_p3;
    ap_return_13 <= res_13_0_fu_478_p3;
    ap_return_14 <= res_1445_0_fu_502_p3;
    ap_return_15 <= res_15_0_fu_526_p3;
    ap_return_2 <= res_2_0_fu_214_p3;
    ap_return_3 <= res_3_0_fu_238_p3;
    ap_return_4 <= res_4_0_fu_262_p3;
    ap_return_5 <= res_5_0_fu_286_p3;
    ap_return_6 <= res_6_0_fu_310_p3;
    ap_return_7 <= res_7_0_fu_334_p3;
    ap_return_8 <= res_8_0_fu_358_p3;
    ap_return_9 <= res_9_0_fu_382_p3;
    icmp_ln45_10_fu_390_p2 <= "1" when (signed(data_10_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_11_fu_414_p2 <= "1" when (signed(data_11_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_12_fu_438_p2 <= "1" when (signed(data_12_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_13_fu_462_p2 <= "1" when (signed(data_13_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_14_fu_486_p2 <= "1" when (signed(data_14_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_15_fu_510_p2 <= "1" when (signed(data_15_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_1_fu_174_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_2_fu_198_p2 <= "1" when (signed(data_2_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_3_fu_222_p2 <= "1" when (signed(data_3_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_4_fu_246_p2 <= "1" when (signed(data_4_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_5_fu_270_p2 <= "1" when (signed(data_5_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_6_fu_294_p2 <= "1" when (signed(data_6_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_7_fu_318_p2 <= "1" when (signed(data_7_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_8_fu_342_p2 <= "1" when (signed(data_8_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_9_fu_366_p2 <= "1" when (signed(data_9_val) > signed(ap_const_lv38_0)) else "0";
    icmp_ln45_fu_150_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv38_0)) else "0";
    res_0_0_fu_166_p3 <= 
        trunc_ln_fu_156_p4 when (icmp_ln45_fu_150_p2(0) = '1') else 
        ap_const_lv16_0;
    res_10_0_fu_406_p3 <= 
        trunc_ln46_s_fu_396_p4 when (icmp_ln45_10_fu_390_p2(0) = '1') else 
        ap_const_lv16_0;
    res_11_0_fu_430_p3 <= 
        trunc_ln46_10_fu_420_p4 when (icmp_ln45_11_fu_414_p2(0) = '1') else 
        ap_const_lv16_0;
    res_12_0_fu_454_p3 <= 
        trunc_ln46_11_fu_444_p4 when (icmp_ln45_12_fu_438_p2(0) = '1') else 
        ap_const_lv16_0;
    res_13_0_fu_478_p3 <= 
        trunc_ln46_12_fu_468_p4 when (icmp_ln45_13_fu_462_p2(0) = '1') else 
        ap_const_lv16_0;
    res_1445_0_fu_502_p3 <= 
        trunc_ln46_13_fu_492_p4 when (icmp_ln45_14_fu_486_p2(0) = '1') else 
        ap_const_lv16_0;
    res_15_0_fu_526_p3 <= 
        trunc_ln46_14_fu_516_p4 when (icmp_ln45_15_fu_510_p2(0) = '1') else 
        ap_const_lv16_0;
    res_1_0_fu_190_p3 <= 
        trunc_ln46_1_fu_180_p4 when (icmp_ln45_1_fu_174_p2(0) = '1') else 
        ap_const_lv16_0;
    res_2_0_fu_214_p3 <= 
        trunc_ln46_2_fu_204_p4 when (icmp_ln45_2_fu_198_p2(0) = '1') else 
        ap_const_lv16_0;
    res_3_0_fu_238_p3 <= 
        trunc_ln46_3_fu_228_p4 when (icmp_ln45_3_fu_222_p2(0) = '1') else 
        ap_const_lv16_0;
    res_4_0_fu_262_p3 <= 
        trunc_ln46_4_fu_252_p4 when (icmp_ln45_4_fu_246_p2(0) = '1') else 
        ap_const_lv16_0;
    res_5_0_fu_286_p3 <= 
        trunc_ln46_5_fu_276_p4 when (icmp_ln45_5_fu_270_p2(0) = '1') else 
        ap_const_lv16_0;
    res_6_0_fu_310_p3 <= 
        trunc_ln46_6_fu_300_p4 when (icmp_ln45_6_fu_294_p2(0) = '1') else 
        ap_const_lv16_0;
    res_7_0_fu_334_p3 <= 
        trunc_ln46_7_fu_324_p4 when (icmp_ln45_7_fu_318_p2(0) = '1') else 
        ap_const_lv16_0;
    res_8_0_fu_358_p3 <= 
        trunc_ln46_8_fu_348_p4 when (icmp_ln45_8_fu_342_p2(0) = '1') else 
        ap_const_lv16_0;
    res_9_0_fu_382_p3 <= 
        trunc_ln46_9_fu_372_p4 when (icmp_ln45_9_fu_366_p2(0) = '1') else 
        ap_const_lv16_0;
    trunc_ln46_10_fu_420_p4 <= data_11_val(25 downto 10);
    trunc_ln46_11_fu_444_p4 <= data_12_val(25 downto 10);
    trunc_ln46_12_fu_468_p4 <= data_13_val(25 downto 10);
    trunc_ln46_13_fu_492_p4 <= data_14_val(25 downto 10);
    trunc_ln46_14_fu_516_p4 <= data_15_val(25 downto 10);
    trunc_ln46_1_fu_180_p4 <= data_1_val(25 downto 10);
    trunc_ln46_2_fu_204_p4 <= data_2_val(25 downto 10);
    trunc_ln46_3_fu_228_p4 <= data_3_val(25 downto 10);
    trunc_ln46_4_fu_252_p4 <= data_4_val(25 downto 10);
    trunc_ln46_5_fu_276_p4 <= data_5_val(25 downto 10);
    trunc_ln46_6_fu_300_p4 <= data_6_val(25 downto 10);
    trunc_ln46_7_fu_324_p4 <= data_7_val(25 downto 10);
    trunc_ln46_8_fu_348_p4 <= data_8_val(25 downto 10);
    trunc_ln46_9_fu_372_p4 <= data_9_val(25 downto 10);
    trunc_ln46_s_fu_396_p4 <= data_10_val(25 downto 10);
    trunc_ln_fu_156_p4 <= data_0_val(25 downto 10);
end behav;
