// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject_myproject,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a15t-cpg236-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.353750,HLS_SYN_LAT=24,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=128151,HLS_SYN_LUT=40231,HLS_VERSION=2024_1}" *)

module myproject (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_ap_vld,
        x,
        layer7_out_0,
        layer7_out_0_ap_vld,
        layer7_out_1,
        layer7_out_1_ap_vld,
        layer7_out_2,
        layer7_out_2_ap_vld,
        layer7_out_3,
        layer7_out_3_ap_vld,
        layer7_out_4,
        layer7_out_4_ap_vld,
        layer7_out_5,
        layer7_out_5_ap_vld,
        layer7_out_6,
        layer7_out_6_ap_vld,
        layer7_out_7,
        layer7_out_7_ap_vld,
        layer7_out_8,
        layer7_out_8_ap_vld,
        layer7_out_9,
        layer7_out_9_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   x_ap_vld;
input  [399:0] x;
output  [36:0] layer7_out_0;
output   layer7_out_0_ap_vld;
output  [36:0] layer7_out_1;
output   layer7_out_1_ap_vld;
output  [36:0] layer7_out_2;
output   layer7_out_2_ap_vld;
output  [36:0] layer7_out_3;
output   layer7_out_3_ap_vld;
output  [36:0] layer7_out_4;
output   layer7_out_4_ap_vld;
output  [36:0] layer7_out_5;
output   layer7_out_5_ap_vld;
output  [36:0] layer7_out_6;
output   layer7_out_6_ap_vld;
output  [36:0] layer7_out_7;
output   layer7_out_7_ap_vld;
output  [36:0] layer7_out_8;
output   layer7_out_8_ap_vld;
output  [36:0] layer7_out_9;
output   layer7_out_9_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer7_out_0_ap_vld;
reg layer7_out_1_ap_vld;
reg layer7_out_2_ap_vld;
reg layer7_out_3_ap_vld;
reg layer7_out_4_ap_vld;
reg layer7_out_5_ap_vld;
reg layer7_out_6_ap_vld;
reg layer7_out_7_ap_vld;
reg layer7_out_8_ap_vld;
reg layer7_out_9_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_idle_pp0;
reg    x_ap_vld_in_sig;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg   [399:0] x_preg;
reg   [399:0] x_in_sig;
reg    x_ap_vld_preg;
reg    x_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [37:0] layer3_out_reg_687;
reg   [37:0] layer3_out_1_reg_692;
reg   [37:0] layer3_out_2_reg_697;
reg   [37:0] layer3_out_3_reg_702;
reg   [37:0] layer3_out_4_reg_707;
reg   [37:0] layer3_out_5_reg_712;
reg   [37:0] layer3_out_6_reg_717;
reg   [37:0] layer3_out_7_reg_722;
reg   [37:0] layer3_out_8_reg_727;
reg   [37:0] layer3_out_9_reg_732;
reg   [37:0] layer3_out_10_reg_737;
reg   [37:0] layer3_out_11_reg_742;
reg   [37:0] layer3_out_12_reg_747;
reg   [37:0] layer3_out_13_reg_752;
reg   [37:0] layer3_out_14_reg_757;
reg   [37:0] layer3_out_15_reg_762;
reg   [37:0] layer3_out_16_reg_767;
reg   [37:0] layer3_out_17_reg_772;
reg   [37:0] layer3_out_18_reg_777;
reg   [37:0] layer3_out_19_reg_782;
reg   [37:0] layer3_out_20_reg_787;
reg   [37:0] layer3_out_21_reg_792;
reg   [37:0] layer3_out_22_reg_797;
reg   [37:0] layer3_out_23_reg_802;
reg   [37:0] layer3_out_24_reg_807;
reg   [37:0] layer3_out_25_reg_812;
reg   [37:0] layer3_out_26_reg_817;
reg   [37:0] layer3_out_27_reg_822;
reg   [37:0] layer3_out_28_reg_827;
reg   [37:0] layer3_out_29_reg_832;
reg   [37:0] layer3_out_30_reg_837;
reg   [37:0] layer3_out_31_reg_842;
reg   [15:0] layer4_out_reg_847;
reg   [15:0] layer4_out_1_reg_852;
reg   [15:0] layer4_out_2_reg_857;
reg   [15:0] layer4_out_3_reg_862;
reg   [15:0] layer4_out_4_reg_867;
reg   [15:0] layer4_out_5_reg_872;
reg   [15:0] layer4_out_6_reg_877;
reg   [15:0] layer4_out_7_reg_882;
reg   [15:0] layer4_out_8_reg_887;
reg   [15:0] layer4_out_9_reg_892;
reg   [15:0] layer4_out_10_reg_897;
reg   [15:0] layer4_out_11_reg_902;
reg   [15:0] layer4_out_12_reg_907;
reg   [15:0] layer4_out_13_reg_912;
reg   [15:0] layer4_out_14_reg_917;
reg   [15:0] layer4_out_15_reg_922;
reg   [15:0] layer4_out_16_reg_927;
reg   [15:0] layer4_out_17_reg_932;
reg   [15:0] layer4_out_18_reg_937;
reg   [15:0] layer4_out_19_reg_942;
reg   [15:0] layer4_out_20_reg_947;
reg   [15:0] layer4_out_21_reg_952;
reg   [15:0] layer4_out_22_reg_957;
reg   [15:0] layer4_out_23_reg_962;
reg   [15:0] layer4_out_24_reg_967;
reg   [15:0] layer4_out_25_reg_972;
reg   [15:0] layer4_out_26_reg_977;
reg   [15:0] layer4_out_27_reg_982;
reg   [15:0] layer4_out_28_reg_987;
reg   [15:0] layer4_out_29_reg_992;
reg   [15:0] layer4_out_30_reg_997;
reg   [15:0] layer4_out_31_reg_1002;
reg   [37:0] layer5_out_reg_1007;
reg   [37:0] layer5_out_1_reg_1012;
reg   [37:0] layer5_out_2_reg_1017;
reg   [37:0] layer5_out_3_reg_1022;
reg   [37:0] layer5_out_4_reg_1027;
reg   [37:0] layer5_out_5_reg_1032;
reg   [37:0] layer5_out_6_reg_1037;
reg   [37:0] layer5_out_7_reg_1042;
reg   [37:0] layer5_out_8_reg_1047;
reg   [37:0] layer5_out_9_reg_1052;
reg   [37:0] layer5_out_10_reg_1057;
reg   [37:0] layer5_out_11_reg_1062;
reg   [37:0] layer5_out_12_reg_1067;
reg   [37:0] layer5_out_13_reg_1072;
reg   [37:0] layer5_out_14_reg_1077;
reg   [37:0] layer5_out_15_reg_1082;
reg   [15:0] layer6_out_reg_1087;
reg   [15:0] layer6_out_1_reg_1092;
reg   [15:0] layer6_out_2_reg_1097;
reg   [15:0] layer6_out_3_reg_1102;
reg   [15:0] layer6_out_4_reg_1107;
reg   [15:0] layer6_out_5_reg_1112;
reg   [15:0] layer6_out_6_reg_1117;
reg   [15:0] layer6_out_7_reg_1122;
reg   [15:0] layer6_out_8_reg_1127;
reg   [15:0] layer6_out_9_reg_1132;
reg   [15:0] layer6_out_10_reg_1137;
reg   [15:0] layer6_out_11_reg_1142;
reg   [15:0] layer6_out_12_reg_1147;
reg   [15:0] layer6_out_13_reg_1152;
reg   [15:0] layer6_out_14_reg_1157;
reg   [15:0] layer6_out_15_reg_1162;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_0;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_1;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_2;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_3;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_4;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_5;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_6;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_7;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_8;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_9;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_10;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_11;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_12;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_13;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_14;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_15;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_16;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_17;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_18;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_19;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_20;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_21;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_22;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_23;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_24;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_25;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_26;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_27;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_28;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_29;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_30;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_31;
reg    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call25;
reg    ap_block_pp0_stage0_11001_ignoreCallOp27;
wire    call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_ready;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_0;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_1;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_2;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_3;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_4;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_5;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_6;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_7;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_8;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_9;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_10;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_11;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_12;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_13;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_14;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_15;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_16;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_17;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_18;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_19;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_20;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_21;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_22;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_23;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_24;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_25;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_26;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_27;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_28;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_29;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_30;
wire   [15:0] call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_31;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_0;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_1;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_2;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_3;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_4;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_5;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_6;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_7;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_8;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_9;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_10;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_11;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_12;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_13;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_14;
wire   [37:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_15;
reg    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call91;
reg    ap_block_pp0_stage0_11001_ignoreCallOp100;
wire    call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_ready;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_0;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_1;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_2;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_3;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_4;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_5;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_6;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_7;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_8;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_9;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_10;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_11;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_12;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_13;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_14;
wire   [15:0] call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_15;
wire   [36:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_0;
wire   [36:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_1;
wire   [36:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_2;
wire   [36:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_3;
wire   [36:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_4;
wire   [36:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_5;
wire   [36:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_6;
wire   [36:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_7;
wire   [36:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_8;
wire   [36:0] grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_9;
reg    grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call125;
reg    ap_block_pp0_stage0_11001_ignoreCallOp141;
wire    ap_block_pp0_stage0_ignoreCallOp27;
wire    ap_block_pp0_stage0_ignoreCallOp67;
wire    ap_block_pp0_stage0_ignoreCallOp100;
wire    ap_block_pp0_stage0_ignoreCallOp124;
wire    ap_block_pp0_stage0_ignoreCallOp141;
reg    ap_block_pp0_stage0_01001;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to23;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 x_preg = 400'd0;
#0 x_ap_vld_preg = 1'b0;
end

myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_val(x_in_sig),
    .ap_return_0(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_4),
    .ap_return_5(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_5),
    .ap_return_6(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_6),
    .ap_return_7(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_7),
    .ap_return_8(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_8),
    .ap_return_9(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_9),
    .ap_return_10(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_10),
    .ap_return_11(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_11),
    .ap_return_12(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_12),
    .ap_return_13(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_13),
    .ap_return_14(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_14),
    .ap_return_15(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_15),
    .ap_return_16(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_16),
    .ap_return_17(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_17),
    .ap_return_18(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_18),
    .ap_return_19(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_19),
    .ap_return_20(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_20),
    .ap_return_21(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_21),
    .ap_return_22(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_22),
    .ap_return_23(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_23),
    .ap_return_24(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_24),
    .ap_return_25(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_25),
    .ap_return_26(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_26),
    .ap_return_27(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_27),
    .ap_return_28(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_28),
    .ap_return_29(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_29),
    .ap_return_30(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_30),
    .ap_return_31(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_31),
    .ap_ce(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_ce)
);

myproject_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136(
    .ap_ready(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_ready),
    .data_0_val(layer3_out_reg_687),
    .data_1_val(layer3_out_1_reg_692),
    .data_2_val(layer3_out_2_reg_697),
    .data_3_val(layer3_out_3_reg_702),
    .data_4_val(layer3_out_4_reg_707),
    .data_5_val(layer3_out_5_reg_712),
    .data_6_val(layer3_out_6_reg_717),
    .data_7_val(layer3_out_7_reg_722),
    .data_8_val(layer3_out_8_reg_727),
    .data_9_val(layer3_out_9_reg_732),
    .data_10_val(layer3_out_10_reg_737),
    .data_11_val(layer3_out_11_reg_742),
    .data_12_val(layer3_out_12_reg_747),
    .data_13_val(layer3_out_13_reg_752),
    .data_14_val(layer3_out_14_reg_757),
    .data_15_val(layer3_out_15_reg_762),
    .data_16_val(layer3_out_16_reg_767),
    .data_17_val(layer3_out_17_reg_772),
    .data_18_val(layer3_out_18_reg_777),
    .data_19_val(layer3_out_19_reg_782),
    .data_20_val(layer3_out_20_reg_787),
    .data_21_val(layer3_out_21_reg_792),
    .data_22_val(layer3_out_22_reg_797),
    .data_23_val(layer3_out_23_reg_802),
    .data_24_val(layer3_out_24_reg_807),
    .data_25_val(layer3_out_25_reg_812),
    .data_26_val(layer3_out_26_reg_817),
    .data_27_val(layer3_out_27_reg_822),
    .data_28_val(layer3_out_28_reg_827),
    .data_29_val(layer3_out_29_reg_832),
    .data_30_val(layer3_out_30_reg_837),
    .data_31_val(layer3_out_31_reg_842),
    .ap_return_0(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_0),
    .ap_return_1(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_1),
    .ap_return_2(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_2),
    .ap_return_3(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_3),
    .ap_return_4(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_4),
    .ap_return_5(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_5),
    .ap_return_6(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_6),
    .ap_return_7(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_7),
    .ap_return_8(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_8),
    .ap_return_9(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_9),
    .ap_return_10(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_10),
    .ap_return_11(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_11),
    .ap_return_12(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_12),
    .ap_return_13(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_13),
    .ap_return_14(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_14),
    .ap_return_15(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_15),
    .ap_return_16(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_16),
    .ap_return_17(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_17),
    .ap_return_18(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_18),
    .ap_return_19(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_19),
    .ap_return_20(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_20),
    .ap_return_21(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_21),
    .ap_return_22(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_22),
    .ap_return_23(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_23),
    .ap_return_24(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_24),
    .ap_return_25(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_25),
    .ap_return_26(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_26),
    .ap_return_27(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_27),
    .ap_return_28(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_28),
    .ap_return_29(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_29),
    .ap_return_30(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_30),
    .ap_return_31(call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_31),
    .ap_rst(ap_rst)
);

myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_0_val(layer4_out_reg_847),
    .data_1_val(layer4_out_1_reg_852),
    .data_2_val(layer4_out_2_reg_857),
    .data_3_val(layer4_out_3_reg_862),
    .data_4_val(layer4_out_4_reg_867),
    .data_5_val(layer4_out_5_reg_872),
    .data_6_val(layer4_out_6_reg_877),
    .data_7_val(layer4_out_7_reg_882),
    .data_8_val(layer4_out_8_reg_887),
    .data_9_val(layer4_out_9_reg_892),
    .data_10_val(layer4_out_10_reg_897),
    .data_11_val(layer4_out_11_reg_902),
    .data_12_val(layer4_out_12_reg_907),
    .data_13_val(layer4_out_13_reg_912),
    .data_14_val(layer4_out_14_reg_917),
    .data_15_val(layer4_out_15_reg_922),
    .data_16_val(layer4_out_16_reg_927),
    .data_17_val(layer4_out_17_reg_932),
    .data_18_val(layer4_out_18_reg_937),
    .data_19_val(layer4_out_19_reg_942),
    .data_20_val(layer4_out_20_reg_947),
    .data_21_val(layer4_out_21_reg_952),
    .data_22_val(layer4_out_22_reg_957),
    .data_23_val(layer4_out_23_reg_962),
    .data_24_val(layer4_out_24_reg_967),
    .data_25_val(layer4_out_25_reg_972),
    .data_26_val(layer4_out_26_reg_977),
    .data_27_val(layer4_out_27_reg_982),
    .data_28_val(layer4_out_28_reg_987),
    .data_29_val(layer4_out_29_reg_992),
    .data_30_val(layer4_out_30_reg_997),
    .data_31_val(layer4_out_31_reg_1002),
    .ap_return_0(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_4),
    .ap_return_5(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_5),
    .ap_return_6(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_6),
    .ap_return_7(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_7),
    .ap_return_8(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_8),
    .ap_return_9(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_9),
    .ap_return_10(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_10),
    .ap_return_11(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_11),
    .ap_return_12(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_12),
    .ap_return_13(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_13),
    .ap_return_14(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_14),
    .ap_return_15(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_15),
    .ap_ce(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_ce)
);

myproject_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208(
    .ap_ready(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_ready),
    .data_0_val(layer5_out_reg_1007),
    .data_1_val(layer5_out_1_reg_1012),
    .data_2_val(layer5_out_2_reg_1017),
    .data_3_val(layer5_out_3_reg_1022),
    .data_4_val(layer5_out_4_reg_1027),
    .data_5_val(layer5_out_5_reg_1032),
    .data_6_val(layer5_out_6_reg_1037),
    .data_7_val(layer5_out_7_reg_1042),
    .data_8_val(layer5_out_8_reg_1047),
    .data_9_val(layer5_out_9_reg_1052),
    .data_10_val(layer5_out_10_reg_1057),
    .data_11_val(layer5_out_11_reg_1062),
    .data_12_val(layer5_out_12_reg_1067),
    .data_13_val(layer5_out_13_reg_1072),
    .data_14_val(layer5_out_14_reg_1077),
    .data_15_val(layer5_out_15_reg_1082),
    .ap_return_0(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_0),
    .ap_return_1(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_1),
    .ap_return_2(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_2),
    .ap_return_3(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_3),
    .ap_return_4(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_4),
    .ap_return_5(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_5),
    .ap_return_6(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_6),
    .ap_return_7(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_7),
    .ap_return_8(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_8),
    .ap_return_9(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_9),
    .ap_return_10(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_10),
    .ap_return_11(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_11),
    .ap_return_12(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_12),
    .ap_return_13(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_13),
    .ap_return_14(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_14),
    .ap_return_15(call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_15),
    .ap_rst(ap_rst)
);

myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_0_val(layer6_out_reg_1087),
    .data_1_val(layer6_out_1_reg_1092),
    .data_2_val(layer6_out_2_reg_1097),
    .data_3_val(layer6_out_3_reg_1102),
    .data_4_val(layer6_out_4_reg_1107),
    .data_5_val(layer6_out_5_reg_1112),
    .data_6_val(layer6_out_6_reg_1117),
    .data_7_val(layer6_out_7_reg_1122),
    .data_8_val(layer6_out_8_reg_1127),
    .data_9_val(layer6_out_9_reg_1132),
    .data_10_val(layer6_out_10_reg_1137),
    .data_11_val(layer6_out_11_reg_1142),
    .data_12_val(layer6_out_12_reg_1147),
    .data_13_val(layer6_out_13_reg_1152),
    .data_14_val(layer6_out_14_reg_1157),
    .data_15_val(layer6_out_15_reg_1162),
    .ap_return_0(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_4),
    .ap_return_5(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_5),
    .ap_return_6(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_6),
    .ap_return_7(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_7),
    .ap_return_8(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_8),
    .ap_return_9(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_9),
    .ap_ce(grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        x_ap_vld_preg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            x_ap_vld_preg <= 1'b0;
        end else if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (x_ap_vld == 1'b1))) begin
            x_ap_vld_preg <= x_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        x_preg <= 400'd0;
    end else begin
        if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (x_ap_vld == 1'b1))) begin
            x_preg <= x;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        layer3_out_10_reg_737 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_10;
        layer3_out_11_reg_742 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_11;
        layer3_out_12_reg_747 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_12;
        layer3_out_13_reg_752 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_13;
        layer3_out_14_reg_757 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_14;
        layer3_out_15_reg_762 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_15;
        layer3_out_16_reg_767 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_16;
        layer3_out_17_reg_772 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_17;
        layer3_out_18_reg_777 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_18;
        layer3_out_19_reg_782 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_19;
        layer3_out_1_reg_692 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_1;
        layer3_out_20_reg_787 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_20;
        layer3_out_21_reg_792 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_21;
        layer3_out_22_reg_797 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_22;
        layer3_out_23_reg_802 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_23;
        layer3_out_24_reg_807 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_24;
        layer3_out_25_reg_812 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_25;
        layer3_out_26_reg_817 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_26;
        layer3_out_27_reg_822 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_27;
        layer3_out_28_reg_827 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_28;
        layer3_out_29_reg_832 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_29;
        layer3_out_2_reg_697 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_2;
        layer3_out_30_reg_837 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_30;
        layer3_out_31_reg_842 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_31;
        layer3_out_3_reg_702 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_3;
        layer3_out_4_reg_707 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_4;
        layer3_out_5_reg_712 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_5;
        layer3_out_6_reg_717 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_6;
        layer3_out_7_reg_722 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_7;
        layer3_out_8_reg_727 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_8;
        layer3_out_9_reg_732 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_9;
        layer3_out_reg_687 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_return_0;
        layer4_out_10_reg_897 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_10;
        layer4_out_11_reg_902 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_11;
        layer4_out_12_reg_907 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_12;
        layer4_out_13_reg_912 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_13;
        layer4_out_14_reg_917 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_14;
        layer4_out_15_reg_922 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_15;
        layer4_out_16_reg_927 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_16;
        layer4_out_17_reg_932 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_17;
        layer4_out_18_reg_937 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_18;
        layer4_out_19_reg_942 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_19;
        layer4_out_1_reg_852 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_1;
        layer4_out_20_reg_947 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_20;
        layer4_out_21_reg_952 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_21;
        layer4_out_22_reg_957 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_22;
        layer4_out_23_reg_962 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_23;
        layer4_out_24_reg_967 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_24;
        layer4_out_25_reg_972 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_25;
        layer4_out_26_reg_977 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_26;
        layer4_out_27_reg_982 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_27;
        layer4_out_28_reg_987 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_28;
        layer4_out_29_reg_992 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_29;
        layer4_out_2_reg_857 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_2;
        layer4_out_30_reg_997 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_30;
        layer4_out_31_reg_1002 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_31;
        layer4_out_3_reg_862 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_3;
        layer4_out_4_reg_867 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_4;
        layer4_out_5_reg_872 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_5;
        layer4_out_6_reg_877 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_6;
        layer4_out_7_reg_882 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_7;
        layer4_out_8_reg_887 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_8;
        layer4_out_9_reg_892 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_9;
        layer4_out_reg_847 <= call_ret2_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config4_s_fu_136_ap_return_0;
        layer5_out_10_reg_1057 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_10;
        layer5_out_11_reg_1062 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_11;
        layer5_out_12_reg_1067 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_12;
        layer5_out_13_reg_1072 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_13;
        layer5_out_14_reg_1077 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_14;
        layer5_out_15_reg_1082 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_15;
        layer5_out_1_reg_1012 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_1;
        layer5_out_2_reg_1017 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_2;
        layer5_out_3_reg_1022 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_3;
        layer5_out_4_reg_1027 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_4;
        layer5_out_5_reg_1032 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_5;
        layer5_out_6_reg_1037 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_6;
        layer5_out_7_reg_1042 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_7;
        layer5_out_8_reg_1047 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_8;
        layer5_out_9_reg_1052 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_9;
        layer5_out_reg_1007 <= grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_return_0;
        layer6_out_10_reg_1137 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_10;
        layer6_out_11_reg_1142 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_11;
        layer6_out_12_reg_1147 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_12;
        layer6_out_13_reg_1152 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_13;
        layer6_out_14_reg_1157 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_14;
        layer6_out_15_reg_1162 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_15;
        layer6_out_1_reg_1092 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_1;
        layer6_out_2_reg_1097 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_2;
        layer6_out_3_reg_1102 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_3;
        layer6_out_4_reg_1107 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_4;
        layer6_out_5_reg_1112 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_5;
        layer6_out_6_reg_1117 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_6;
        layer6_out_7_reg_1122 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_7;
        layer6_out_8_reg_1127 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_8;
        layer6_out_9_reg_1132 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_9;
        layer6_out_reg_1087 <= call_ret_relu_ap_fixed_38_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config6_s_fu_208_ap_return_0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to23 = 1'b1;
    end else begin
        ap_idle_pp0_0to23 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to23 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp141))) begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp27))) begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config3_s_fu_130_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp100))) begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_38_18_5_3_0_config5_s_fu_172_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer7_out_0_ap_vld = 1'b1;
    end else begin
        layer7_out_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer7_out_1_ap_vld = 1'b1;
    end else begin
        layer7_out_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer7_out_2_ap_vld = 1'b1;
    end else begin
        layer7_out_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer7_out_3_ap_vld = 1'b1;
    end else begin
        layer7_out_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer7_out_4_ap_vld = 1'b1;
    end else begin
        layer7_out_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer7_out_5_ap_vld = 1'b1;
    end else begin
        layer7_out_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer7_out_6_ap_vld = 1'b1;
    end else begin
        layer7_out_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer7_out_7_ap_vld = 1'b1;
    end else begin
        layer7_out_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer7_out_8_ap_vld = 1'b1;
    end else begin
        layer7_out_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer7_out_9_ap_vld = 1'b1;
    end else begin
        layer7_out_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((x_ap_vld == 1'b1)) begin
        x_ap_vld_in_sig = x_ap_vld;
    end else begin
        x_ap_vld_in_sig = x_ap_vld_preg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        x_blk_n = x_ap_vld;
    end else begin
        x_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((x_ap_vld == 1'b1)) begin
        x_in_sig = x;
    end else begin
        x_in_sig = x_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp100 = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_ignore_call91));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp141 = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_ignore_call125));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp27 = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_ignore_call25));
end

assign ap_block_pp0_stage0_ignoreCallOp100 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp124 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp141 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp27 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp67 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (x_ap_vld_in_sig == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call125 = (x_ap_vld_in_sig == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call25 = (x_ap_vld_in_sig == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call91 = (x_ap_vld_in_sig == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign layer7_out_0 = grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_0;

assign layer7_out_1 = grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_1;

assign layer7_out_2 = grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_2;

assign layer7_out_3 = grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_3;

assign layer7_out_4 = grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_4;

assign layer7_out_5 = grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_5;

assign layer7_out_6 = grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_6;

assign layer7_out_7 = grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_7;

assign layer7_out_8 = grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_8;

assign layer7_out_9 = grp_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config7_s_fu_228_ap_return_9;

endmodule //myproject
